# Generated by Django 4.1.3 on 2023-05-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopkeeper', models.CharField(blank=True, max_length=99, null=True)),
                ('username', models.CharField(blank=True, max_length=99, null=True)),
                ('shopname', models.CharField(blank=True, max_length=99, null=True)),
                ('shoplocation', models.CharField(blank=True, max_length=99, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
