# Generated by Django 4.1.3 on 2023-05-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplist',
            name='shopphoto',
            field=models.ImageField(blank=True, null=True, upload_to='shop_photo/'),
        ),
    ]
