# Generated by Django 4.1.3 on 2023-05-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pdfdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdatabase',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
