# Generated by Django 4.1.3 on 2023-05-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pdfdatabase_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdatabase',
            name='sfenderusername',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
