# Generated by Django 4.1.3 on 2023-05-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pdfdatabase_sfenderusername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfdatabase',
            old_name='sfenderusername',
            new_name='senderusername',
        ),
    ]
