# Generated by Django 4.1.3 on 2023-05-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_sfenderusername_pdfdatabase_senderusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdatabase',
            name='selectshopname',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
