# Generated by Django 4.2.1 on 2023-05-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_pdfdatabase_selectshopname'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdatabase',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=99, null=True),
        ),
    ]
