# Generated by Django 4.2.1 on 2023-06-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_pdfdatabase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdatabase',
            name='total_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
