# Generated by Django 4.2.1 on 2023-06-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_pdfdatabase_total_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdatabase',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdatabase',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdatabase',
            name='transaction',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
