# Generated by Django 4.2.1 on 2023-06-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_pdfdatabase_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdatabase',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='pdfdatabase',
            name='total_page',
        ),
        migrations.RemoveField(
            model_name='pdfdatabase',
            name='transaction',
        ),
    ]
