# Generated by Django 4.2.1 on 2023-06-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_pdfdatabase_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdatabase',
            name='total_cost',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pdfdatabase',
            name='total_page',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pdfdatabase',
            name='transaction',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
