# Generated by Django 4.2.1 on 2023-06-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_pdfdatabase_total_cost_pdfdatabase_total_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdatabase',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatabase',
            name='total_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
