# Generated by Django 4.2.1 on 2023-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_pdfdatabase_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdatabase',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
