# Generated by Django 4.2.1 on 2023-07-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_pdfdatabase_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(blank=True, max_length=99, null=True)),
                ('course_name', models.CharField(blank=True, max_length=99, null=True)),
                ('short_description', models.CharField(blank=True, max_length=99, null=True)),
                ('instructor', models.CharField(blank=True, max_length=99, null=True)),
                ('syllabus', models.CharField(blank=True, max_length=99, null=True)),
                ('description', models.CharField(blank=True, max_length=99, null=True)),
                ('duration', models.CharField(blank=True, max_length=99, null=True)),
            ],
        ),
    ]
